### ISSUE TITLE
Failure to merge: winp sometimes kills random processes when using killRecursive

### ISSUE THREAD

**Issue by benhumphreys** [kohsuke/winp#22]
The following issue describes a problem still present in *winp* due to a failure to merge the pull request correctly: [winp sometimes kills random processes when using killRecursive](https://github.com/kohsuke/winp/issues/6)

Specifically this pull request was not correctly merged: https://github.com/kohsuke/winp/pull/8

A simple check would seem to indicate the commit was merged:

```
$ git tag --contains 27a1f7ca64f4dfa0f243dfc834e671ffc3c0b8b9
1.23-beta
winp-1.17
winp-1.18
winp-1.19
winp-1.20
winp-1.21
winp-1.22
winp-1.23
```

However the merge (https://github.com/kohsuke/winp/commit/b8595265934ee34229763a92c141a57a23918ded)  actually reverted the change during the merge. Note that `native/winp.cpp` is listed as a conflict. It would appear a merge strategy "ours" was used to resolve the conflict, hence discarding the change.

We encountered this problem only recently because we have been using the `1.17-atlassian1` release of winp (found here https://github.com/bturner/winp/tree/winp-1.17-atlassian1), which does include a fix for the issue, for a long time. We recently upgraded to the 1.19 release from the primary winp repository and have been seeing this problem since.

**Comment by oleg-nenashev** [comment]
You are not the first one. 
#18 seems to be a related issue. Thanks a lot for the analysis. Hopefully I or @kohsuke finally find some time to handle it.

**Comment by gorrus** [comment]
awesome!

**Comment by gorrus** [comment]
any news on this?

**Comment by segrey** [comment]
Any updates/workarounds?

**Comment by oleg-nenashev** [comment]
Unfortunately, no. Have not found time to handle the issue on this summer and then forgotten about it. My apologies.

**Comment by oleg-nenashev** [comment]
I'll try to remerge it later today

**Comment by segrey** [comment]
Cools, thanks for the update!

**Comment by gorrus** [comment]
this is still valid, please do something
