### ISSUE TITLE
Can ProcessBuilder be used to run sendctrlc.exe?

### ISSUE THREAD

**Issue by segrey** [kohsuke/winp#55]
Currently, sendctrlc.exe is spawned in [winp.cpp](https://github.com/kohsuke/winp/blob/a9e44d3094143e4bf8e892f3d5e4fa5a12dc6016/native/winp.cpp#L28).
Is it possible to use java.lang.ProcessBuilder to spawn sendctrlc.exe and, thus, simplify code?
If no, it'd be great to write a comment in code explaining decision.

**Comment by segrey** [comment]
@oleg-nenashev @stephanreiter Any thoughts? I would appreciate your feedback.

**Comment by oleg-nenashev** [comment]
Sorry, missed the previous notification.
IIRC there was a discussion about that in the pull request, will try to find it.
Native code is not considered as API, so we can always change it without breaking changes.

**Comment by stephanreiter** [comment]
Using ProcessBuild is no problem. Good idea! Less native code ...
SendCtrlC ended up in native because it started there with some implementation that didn't use a separate EXE.

**Comment by segrey** [comment]
@oleg-nenashev Thanks. I meant something like
```java
  public static boolean sendCtrlC(int pid) {
    Process process = new ProcessBuilder("sendctrlc.exe", pid).start();
    return waitFor(process, 5000) != null;
  }


  @Nullable
  private static Integer waitFor(@NotNull Process process, int timeoutMillis) {
    long stop = System.currentTimeMillis() + timeoutMillis;
    while (System.currentTimeMillis() < stop) {
      TimeoutUtil.sleep(100);
      try {
        Thread.sleep(100);
        return process.exitValue();
      }
      catch (Exception ignore) {
      }
    }
    return null;
  }
```

This way, ProcessBuilder is not exposed in winp's API, so it can be changed without breaking changes too.

**Comment by stephanreiter** [comment]
Will that terminate the sendctrl.exe process after 5secs? That shouldn't be left lingering.

**Comment by stephanreiter** [comment]
Same should be (made) true for the native code! :)

**Comment by stephanreiter** [comment]
I don't know much about ProcessBuilder anymore. :)

And sendctrlc.exe will first detach from its console, then attach to the <pid> process to avoid what you describe w.r.t. the parent process.

`  FreeConsole();
  if (!AttachConsole(pid)) {
    return GetLastError();
  }
`

**Comment by segrey** [comment]
@stephanreiter Sorry for not being clear. Yes, `sendctrlc.exe` deattaches from its initial console to be able to attach to a console of  the specified process. But what if several processes are already attached to the console, `sendctrlc.exe` tries to attach to? For example, `parent_pid` and `pid` are attached to the same console and `sendctrlc.exe pid` is spawned. Looks like `parent_pid` will receive CtrlC event as well. Honestly, I haven't managed to reproduce such case, just wondering if it's possible.

**Comment by stephanreiter** [comment]
Ah, now I understand. Well, then the Ctrl+C will go to the parent as well. I guess that should be documented to make it obvious.
