### ISSUE TITLE
Flickering console window when sending Ctrl+C

### ISSUE THREAD

**Issue by segrey** [kohsuke/winp#60]
When a process is started without console window, executing `org.jvnet.winp.WinProcess#sendCtrlC` leads to running `sendctrlc.exe` with a new console visible window. Even though `sendctrlc.exe` is a short-living process, the console window flickering is noticeable.

To reproduce the issue, please see [myapp.zip](https://github.com/kohsuke/winp/files/2605915/myapp.zip).
It's a simple Java Swing application running `new WinProcess(123).sendCtrlC()` on button click.
1. Unzip the project and optionally rebuild it.
2. Run the app with `run.cmd`. Or start it manually, just ensure you're using `javaw.exe` instead of `java.exe` to start the process without console window.
3. A window with a single button will appear:
![image](https://user-images.githubusercontent.com/607109/48870926-aff98000-edf3-11e8-8d82-a0acd929b7e1.png)
4. Click it and a console window will appear and hide.

**Comment by segrey** [comment]
I have a patch for this issue based on using `java.lang.ProcessBuilder` and spawn `sendctrlc.exe` from Java instead of doing it in winp.cpp (SendCtrlC). If no objections, I'll open the PR soon.

**Comment by oleg-nenashev** [comment]
sure, please feel free to submit it

**Comment by segrey** [comment]
Suggested fix: PR https://github.com/kohsuke/winp/pull/61

**Comment by segrey** [comment]
Another reported case about flickering window popup: https://youtrack.jetbrains.com/issue/WEB-36921 (IntelliJ IDEA).
@oleg-nenashev Would be great to cut a release.

**Comment by oleg-nenashev** [comment]
@segrey I am still waiting for the new Windows laptop, sorry :(
Let's proceed with #64 which might be a quicker solution. I might get my laptop next week, but it's hard to guarantee

**Comment by segrey** [comment]
Sure, next week is fine. Regarding #64, sorry, can it help to cut a release quicker?

**Comment by oleg-nenashev** [comment]
Let's try to do both.

It is apparently not trivial to revert the environment to the WinP-capable
version to do the release, and I would not like to spend few days on
updating a laptop which should have been decommissioned months ago :(

If it was not Maven Central, I would have already automated releases on
AppVeyor or other CI system.

**Comment by oleg-nenashev** [comment]
Fixed in WinP 1.28
